name: Deploy in EC2
env:
  PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-18-229-117-8.sa-east-1.compute.amazonaws.com '

            #Now we have got the access of EC2 and we will start the deploy .
            DIR="/home/ubuntu/base-graphql-api"
            pm2 delete all
            cd /home/ubuntu

            if [ ! -d $DIR ]
            then
              mkdir base-graphql-api &&
              git clone https://github.com/gabrielmaialva33/base-graphql-api.git base-graphql-api &&
              cd base-graphql-api && npm install yarn -g &&
              sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node" &&
              sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm" &&
              sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2" &&
              yarn && yarn build && yarn db:reset
            else
              cd base-graphql-api
            fi

            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            pm2 start ecosystem.config.js
          '
