

name: GitHub Actions EC2

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}

        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
          cat private_key.pem
          ssh -o StrictHostKeyChecking=no -i "private_key.pem" ubuntu@ec2-18-229-117-8.sa-east-1.compute.amazonaws.com '

            #Now we have got the access of EC2 and we will start the deploy .
            DIR="/home/ubuntu/server"
            pm2 delete all
            cd /home/ubuntu

            if [ ! -d $DIR ]
            then
              mkdir server &&
              git clone https://github.com/CodePanthers/node-aws-ec2-github-actions.git server &&
              cd server &&
              yarn && yarn build && yarn db:reset
            else
              cd server
            fi

            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            pm2 start ecosystem.config.js
          '
